### PR TITLE
RubyGems Monthly Update - August

### PR DESCRIPTION
**Pull request by lauragift21**
Hello, @deivid-rodriguez and @sonalkr132 can you kindly help me go over this draft to ensure I covered the work done in August. I didn't get any update on Slack for the RubyGems section so if there's any additional thing you want me to add please let me know.

Thanks!

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Oh, I'm really sorry @lauragift21, I forgot to post updates this month. I will add some paragraphs about the work done tomorrow!

**Comment by lauragift21** [comment]
> Oh, I'm really sorry @lauragift21, I forgot to post updates this month. I will add some paragraphs about the work done tomorrow!
No worries. thanks!

**Review by sonalkr132 — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
> During the last month, we released [rubygems 3.2.26](https://rubygems.org/gems/rubygems-update/versions/3.2.26) which features experimental support for the `RUBYGEMS_GEMDEPS` environment variable, which allows using locked versions of executables without the need of prepending `bundle exec` to them. It also fixes an issue which rubygems plugin loading and improves reporting of errors inside operating system customizations of rubygems.

> On the bundler side of things we released [bundler 2.2.26](https://rubygems.org/gems/bundler/versions/2.2.26), which includes several small fixes and improvements further detailed in [the changelog](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2226-august-17-2021).

**Comment by lauragift21** [comment]
Got it Thank you! @deivid-rodriguez

**Review by deivid-rodriguez — APPROVED** [review]

**Pull request merged**
