### PR TITLE
Add March RubyGems Updates

### PR DESCRIPTION
**Pull request by lauragift21**
Draft for March monthly updates.

Hi @deivid-rodriguez, can you help review that I captured work done in March correctly thank you!

### CODE REVIEW

**Comment by simi** [comment]
I think it is ok to mention https://github.com/rubygems/rubygems/pull/5175 as well. Just please make it clear it is currently in experimental state and could be changed in the future. My current plan is to make it stable before Ruby 3.2 release.

**Comment by lauragift21** [comment]
> I think it is ok to mention [rubygems/rubygems#5175](https://github.com/rubygems/rubygems/pull/5175) as well. Just please make it clear it is currently in experimental state and could be changed in the future. My current plan is to make it stable before Ruby 3.2 release.

Thanks @simi! Added to the post.

**Comment by deivid-rodriguez** [comment]
Should we save the information about cargo extensions until we actually release it, or alternatively explaining that it's only available when running latest HEAD?

**Comment by simi** [comment]
Ahh, it wasn't released yet? I wasn't aware of this. Indeed we can save this for later or explicitly mention this is in RubyGems HEAD only at the time of this update.

**Comment by deivid-rodriguez** [comment]
Oh, sorry for the confusion. Yeah, I was planning to release it with RubyGems 3.3.10, but I had trouble getting CI to pass in the stable branch, so I decided to skip it for now and aim to release it with RubyGems 3.3.11. This is what I meant with https://github.com/rubygems/rubygems/pull/5420#issuecomment-1076417266 and the rest of the conversation there.

**Comment by deivid-rodriguez** [comment]
Now I see that you probably understood "skip the failing specs for now" rather than "skip shipping the cargo extensions feature for now", sorry for the ambiguity. Since I don't think we were on a hurry to ship it, I preferred to properly investigate the failures before releasing rather than blindly skipping them.

**Comment by simi** [comment]
OK, sorry for the confusion. :pray: :innocent:

**Pull request merged**
